In [221]:
import numpy as np

In [222]:
#task 92:
def is_scalar(k):
    if len(set(k)) == 1:
        return True
    else:
        return False

def are_proportional(A, B):
    k = B / A
    if is_scalar(k):
        print(f"Vectors are proportional, k = {k[0]}")
        return True
    else:
        return False

def are_collinear(A, B, C):
    print(f"A = {A}")
    print(f"B = {B}")
    print(f"C = {C}")
    
    #all dots should be on the same line:
    AB = B - A
    print(f"AB = {AB}")
    AC = C - A
    print(f"AC = {AC}")
    
    if are_proportional(AB, AC):
        print(f"All dots are on the same line\n")
    else:
        print("All dots are not on the same line\n")

#a)
A = np.array([3, 4, 1])
B = np.array([1, 0, -1])
C = np.array([-2, -6, -4])
are_collinear(A, B, C)

#b)
A = np.array([3, 2, -1])
B = np.array([5, -1, 4])
C = np.array([1, -7, 12])
are_collinear(A, B, C)

A = [3 4 1]
B = [ 1  0 -1]
C = [-2 -6 -4]
AB = [-2 -4 -2]
AC = [ -5 -10  -5]
Vectors are proportional, k = 2.5
All dots are on the same line

A = [ 3  2 -1]
B = [ 5 -1  4]
C = [ 1 -7 12]
AB = [ 2 -3  5]
AC = [-2 -9 13]
All dots are not on the same line


In [223]:
#task 93:
A = np.array([-3, 4, -1])
B = np.array([-1, 2, 3])
C = np.array([-4, -2, 1])

x = 4*A + 3*B - 2*C
y = -5*A + 4*B + C
print(f"x = {x}")
print(f"y = {y}")

x = [-7 26  3]
y = [  7 -14  18]


In [224]:
#task 94:
def dot_product(norm_A, norm_B, phi):
    return norm_A * norm_B * np.cos(phi)

norm_A = 5
norm_B = 6
#a)
phi = 45
print(dot_product(norm_A, norm_B, phi))
#b)
phi = 60
print(dot_product(norm_A, norm_B, phi))
#c)
phi = 135
print(dot_product(norm_A, norm_B, phi))

15.759659664531892
-28.57238941245469
-29.882635054235546


In [225]:
#task 101:
def are_coplanar(A, B, C):
    matrix = np.vstack((A, B, C)).transpose()
    det = np.linalg.det(matrix)
    print(f"matrix = \n{matrix}")
    print(f"det = {det}")
    if det == 0:
        print("Vectors are coplanar")
    else:
        print("Vectors are not coplanar")

A = np.array([3, 5, -4])
B = np.array([1, -1, -3])
C = np.array([7, 2, -6])
D = np.array([-1, 3, -2])
AB = B - A
AC = C - A
AD = D - A
print(f"AB = {AB}")
print(f"AC = {AC}")
print(f"AD = {AD}")
are_coplanar(AB, AC, AD)

AB = [-2 -6  1]
AC = [ 4 -3 -2]
AD = [-4 -2  2]
matrix = 
[[-2  4 -4]
 [-6 -3 -2]
 [ 1 -2  2]]
det = 0.0
Vectors are coplanar


In [226]:
#task 104:
a1 = np.array([1, -1, 2, 1])
a2 = np.array([2, 1, -1, 3])
a3 = np.array([6, 0, 2, 8])
a4 = np.array([-1, -2, 3, -2])
a5 = np.array([3, 0, 1, 4])

A = np.vstack((a1, a2, a3, a4, a5))
print(f"A = \n{A}")

linearly_independent_vectors = A[:np.linalg.matrix_rank(A)]
dependent_vectors = A[np.linalg.matrix_rank(A):]

print("linearly independent vectors:")
vector_count = 1
for vector in linearly_independent_vectors:
    print(f"a{vector_count} = {vector}")
    vector_count += 1
    
print("other vectors from linearly independent vectors:")

for vector in dependent_vectors:
    inverted_m = np.linalg.pinv(linearly_independent_vectors.transpose())
    x = np.dot(inverted_m, vector)
    answer = ""
    vector_count = 1
    for i in range(len(x)):
        answer += "a" + str(vector_count) + " * " + str(round(x[i], 10)) + " + "
        vector_count += 1
    print(answer[:-3])

A = 
[[ 1 -1  2  1]
 [ 2  1 -1  3]
 [ 6  0  2  8]
 [-1 -2  3 -2]
 [ 3  0  1  4]]
linearly independent vectors:
a1 = [ 1 -1  2  1]
a2 = [ 2  1 -1  3]
other vectors from linearly independent vectors:
a1 * 2.0 + a2 * 2.0
a1 * 1.0 + a2 * -1.0
a1 * 1.0 + a2 * 1.0


In [227]:
#task 107:
A = np.array([-1, 2, 1])
B = np.array([2, 1, -2])
C = np.array([1, 1, 1])
vector_to_find_in_basis = np.array([-3, 4, 5])

matrix = np.vstack((A, B, C))
print(f"matrix = \n{matrix}")
rank = np.linalg.matrix_rank(matrix)
print(f"rank = {rank}")

if rank == matrix.shape[0] == matrix.shape[1]:
    print("vectors are linearly independent")
    coefficients = np.linalg.solve(matrix, vector_to_find_in_basis)
    print(f"coefficients = {coefficients}")
else:
    print("vectors are linearly dependent")

matrix = 
[[-1  2  1]
 [ 2  1 -2]
 [ 1  1  1]]
rank = 3
vectors are linearly independent
coefficients = [ 3.8 -0.4  1.6]


In [228]:
#task 122:
A = np.array([[5, 6, -3],
             [-1, 0, 1],
             [1, 2, -1]])

eigenvalues, eigenvectors = np.linalg.eig(A)
print(f"eigenvalues = {eigenvalues}")
for i, eigenvalue in enumerate(eigenvalues):
    eigenvector = eigenvectors[:, i]
    print(f"Собственный вектор для собственного значения {eigenvalue}:")
    print(eigenvector)

eigenvalues = [-0.73205081  2.73205081  2.        ]
Собственный вектор для собственного значения -0.7320508075688781:
[ 0.61329046 -0.20443015  0.76294372]
Собственный вектор для собственного значения 2.73205080756888:
[-0.94529591  0.31509864 -0.08443043]
Собственный вектор для собственного значения 1.9999999999999993:
[-8.94427191e-01  4.47213595e-01  4.40659898e-16]


In [229]:
#task 130:
A = np.array([[1, 2, 0],
              [0, 2, 0],
              [-2, -2, -1]])

eigenvalues, eigenvectors = np.linalg.eig(A)

C = eigenvectors
print(np.linalg.matrix_rank(C))
C_inv = np.linalg.inv(C)
D = np.dot(np.dot(C_inv, A), C)
D

3


array([[-1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  2.]])