In [19]:
import numpy as np

In [20]:
#1 (22 task):
A = np.array([[2, -1], [3, 2], [5, -2]])
B = np.array([[-2, -1], [11, -2], [5, 7]])
C = np.array([[1, 3, 0, 4], [0, 2, -3, 5], [5, 3, 10, -2]])
D = np.array([[-2, 5, 1, -3], [1, 1, -5, -4], [2, 6, 11, -1]])

G = np.dot(np.transpose(2 * A + B), (3 * C - 4 * D))
G

array([[  59, -213,  -31,  545],
       [ -20,   -8,   -8,  -16]])

In [21]:
#2 (28 task):
def f(x):
    return 2 * pow(x, 3) + x + 5

A = np.array([[-1, 0], [2, 2]])
f(A)

array([[ 2,  5],
       [23, 23]])

In [22]:
#3 (36 task):
matrix = np.array([[3, 5, 7, 2], [7, 6, 3, 7], [5, 4, 3, 5], [-5, -6, -5, -4]])

det = np.linalg.det(matrix)
det

-9.999999999999936

In [23]:
#4 (50 task):
A = np.array([[-6, -1, 4], [-4, -4, 3], [3, -2, -2]])
inv = np.linalg.inv(A)
inv

array([[-2.8,  2. , -2.6],
       [-0.2, -0. , -0.4],
       [-4. ,  3. , -4. ]])

In [24]:
#5 (51 task):
A = np.array([[-1, -4, 8, 15, -1, 5],
              [-8, 4, -5, 7, -5, 8],
              [7, 3, -14, 7, 8, -2],
              [10, -9, 0, -4, -2, -6],
              [-6, -3, -4, -2, 12, 2],
              [-7, 8, 12, -4, -9, 9]])

B = np.array([[3, -5, 9, 3, -1, 0],
              [5, -3, -5, 0, -5, 13],
              [-6, 10, -4, 15, -2, 0],
              [15, -6, 9, -9, -2, -6],
              [8, -3, 5, -5, 8, -1],
              [0, 8, 6, -4, 12, -7]])

np.linalg.solve(A, B)

array([[ 0.76076373,  1.05154173,  1.27107887,  0.23302265,  0.89376539,
        -1.46613399],
       [-2.13269423,  1.36624602, -0.93009527,  1.39652486,  0.18627268,
        -0.21935091],
       [-0.63217101,  0.2252911 ,  0.46509346,  0.11585065,  0.52686904,
        -0.76047847],
       [-0.88374555, -0.20010642, -0.49929794,  0.85173269, -0.75798208,
         0.61215765],
       [-0.28605571,  0.55021151,  0.52985465,  0.37968128,  0.91898938,
        -0.81416333],
       [ 2.6514965 ,  0.65320096,  2.16985477, -0.90079843,  1.74252488,
        -1.2512476 ]])

In [25]:
#6 (55 task):
B = np.array([[0, 1, -1, 3],
              [2, 5, 1, 11],
              [1, 2, 1, 4]])

np.linalg.matrix_rank(B)

2

In [26]:
#7 (57 task):
B = np.array([[1, 2, 1, 4],
              [0, 5, -1, 4],
              [-1, 3, 4, 6]])

np.linalg.matrix_rank(B)

3

In [27]:
#8 (78 task):
A = np.array ([[3, 2, 1],[2, 3, 1],[2, 1, 3]])
B = np.array([-8, -3, -1])

def solve_slu(A, B):
    Det_A =np.linalg.det(A)
    print(f"Det_A = {Det_A}")
    B1 = B.reshape(1, B.shape[0])
    print(f"B1 = {B1}")
    AB = np.vstack((A, B1))
    print(f"AB = {AB}")
    if Det_A != 0:
        X = np.linalg.solve(A, B)
        print('Единственное решение:')
        print(X)
    if Det_A == 0:
        rank_A = np.linalg.matrix_rank(A)
        rank_AB = np.linalg.matrix_rank(AB)
        if rank_A == rank_AB:
            print ('Система имеет бесконечное множество решений')
        else:
            print ('Система не имеет решений')
    return

solve_slu(A, B)

Det_A = 12.000000000000005
B1 = [[-8 -3 -1]]
AB = [[ 3  2  1]
 [ 2  3  1]
 [ 2  1  3]
 [-8 -3 -1]]
Единственное решение:
[-4.  1.  2.]
